name: Apply Network Policy for tenant namespace
on: 
  workflow_dispatch:
    inputs:
      tenant:
        description: Tenant name. Use lowercase alphanumeric characters az09
        default: Tenant Name
        required: true

env:
  RESOURCEGROUPNAME: "demo-saas-aks"
  CLUSTERNAME: "demo-saas-aks"

jobs:
  netpol:
    name: Network Policy Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # login to azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      id: getContext
      run: |
          az aks get-credentials --resource-group ${{ env.RESOURCEGROUPNAME }} --name ${{ env.CLUSTERNAME }} --file $GITHUB_WORKSPACE/kubeconfig
          echo "KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig" >> $GITHUB_ENV

    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ${{ github.event.inputs.tenant }} | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ${{ github.event.inputs.tenant }}`
        fi

    - name: Apply Network Policy for tenant namespace
      run: |
        sed -e "s/<tenantname>/${{ github.event.inputs.tenant }}/g" ./k8s/netpol.yaml | kubectl apply -f -
        echo `kubectl get netpol -n ${{ github.event.inputs.tenant }}`
    
    - name : Cleanup
      run: | 
        az logout
        rm -rf $GITHUB_WORKSPACE/kubeconfig
